# Modified from https://github.com/ogrisel/python-appveyor-demo

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python33"
      PY_PYTHON: 3.3-32
      PY_PYTHON3: 3.3-32
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PY_PYTHON: 3.3
      PY_PYTHON3: 3.3
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PY_PYTHON: 3.4-32
      PY_PYTHON3: 3.4-32
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PY_PYTHON: 3.4
      PY_PYTHON3: 3.4
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

    # Python 3.5-32 won't run through the C:\Windows\py.exe launcher on
    # AppVeyor for some reason. See:
    # http://help.appveyor.com/discussions/problems/3891-py-35-32-hellopy-fails-with-error-code-103
    # - PYTHON: "C:\\Python35"
    # - PY_PYTHON: 3.5-32
    # - PY_PYTHON3: 3.5-32
    # - PYTHON_VERSION: "3.5.x"
    # - PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PY_PYTHON: 3.5
      PY_PYTHON3: 3.5
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "py -c \"import sys; print(sys.version)\""
  - "py -3 -c \"import sys; print(sys.version)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install -r requirements-dev.txt"

  # The AppVeyor ftype for Python files is hardcoded to the Python 2
  # interpreter, instead of the py.exe launcher. This works around that problem
  # until a fix is in:
  # http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem#comment_38756340
  - ps: cmd /c ftype Python.File="C:\Windows\py.exe" "%1" %*

build: off

test_script:
  - "%CMD_IN_ENV% python test.py -v"
